[uwsgi]
chdir = /var/www/html/djangovuer

module = djangovue.wsgi

home = /var/www/html/djangovuer/apienv

master = true
processes = 4

socket = /var/www/html/djangovuer/uwsgi.sock
chmod-socket = 666

http = :8001

vacuum = true
die-on-term = true

uid = freefire  # Add this
gid = www-data  # Add this

daemonize = /var/www/html/djangovuer/uwsgi-emperor.log