# Generated by Django 5.1.5 on 2025-01-31 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomecoDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')])),
                ('customer_name', models.CharField(max_length=50)),
                ('waybill_number', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Waybill number must be 8 alphanumeric characters', regex='^[A-Za-z0-9]{8}$')])),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Zip code must be 5 digits', regex='^\\d{5}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NovonordisDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')])),
                ('customer_name', models.CharField(max_length=50)),
                ('waybill_number', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Waybill number must be 8 alphanumeric characters', regex='^[A-Za-z0-9]{8}$')])),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Zip code must be 5 digits', regex='^\\d{5}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
