# Generated by Django 5.1.5 on 2025-02-05 14:44

from django.db import migrations, models
from django.conf import settings


def set_default_user(apps, schema_editor):
    APIKey = apps.get_model('APIServer', 'APIKey')
    User = apps.get_model('auth', 'User')
    # Get the first superuser, or create one if none exists
    superuser = User.objects.filter(is_superuser=True).first()
    if not superuser:
        superuser = User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='adminpassword'
        )
    # Update all APIKeys with null user
    APIKey.objects.filter(user__isnull=True).update(user=superuser)


class Migration(migrations.Migration):

    dependencies = [
        ('APIServer', '0005_apikey_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(set_default_user),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='api_keys',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
