[program:bhs_waybill]
directory=${APP_PATH}
command=${VENV_PATH}/bin/gunicorn --workers ${WORKERS} --threads ${THREADS} --bind 127.0.0.1:${PORT} --timeout ${TIMEOUT} app:app
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=${LOG_DIR}/gunicorn.err.log
stdout_logfile=${LOG_DIR}/gunicorn.out.log
